"use client";

import * as React from "react";
import { CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { addDays, weekEnd, nextWeekStart, prevWeekStart } from "@/lib/weekly-goals/week";
import { weekNoOf } from "@/lib/goals/fy-calendar";

/**
 * The Weekly board's period control — the Weekly analogue of the level boards'
 * FY stepper and of Quarterly's quarter window:
 *
 *     [ ‹ | 📅 W19 · 10 Aug – 16 Aug ▾ | › ]
 *
 * Same box as the FY stepper (one rounded hairline group, chevrons flanking a
 * divided centre) so Yearly/Quarterly/Monthly/Weekly read as one product. What
 * differs is the centre: weeks are unbounded, so it is a BUTTON that opens a
 * compact popover instead of a static label.
 *
 * WHY A POPOVER, not a row of week pills: Quarterly can print four quarters and
 * Monthly twelve months, but a year holds 52 weeks — laid out inline they would
 * either dwarf the header or force an arbitrary window with no way back. The
 * popover keeps the header to one control and groups the list the way a planner
 * actually thinks about it — UPCOMING (what I'm planning), CURRENT (where I am),
 * PAST (what I'm reviewing) — with the list scrolling inside a fixed height.
 *
 * Every week here is DERIVED: the list is generated by stepping Mondays off the
 * live current week, and each label's number comes from `weekNoOf` (the FY
 * calendar). No week number, date or range is written down anywhere.
 */

/** How far the list reaches either side of the live week. Both are generous
 *  enough that the popover scrolls — which is the point; the header must never
 *  grow a week list of its own. */
const UPCOMING_WEEKS = 8;
const PAST_WEEKS = 12;

const MONTH_ABBR = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
] as const;

/** "10 Aug" — day + short month, no year. */
function dayMonth(ymd: string): string {
  return `${Number(ymd.slice(8, 10))} ${MONTH_ABBR[Number(ymd.slice(5, 7)) - 1]}`;
}

/**
 * "10 Aug – 16 Aug" for a Monday week-start. The compact sibling of
 * `formatWeekLabel` ("10 AUG 2026 – 16 AUG 2026"), which is right for a drawer
 * eyebrow but too long to sit inside a header control next to "W19".
 */
export function formatWeekRangeShort(weekStart: string): string {
  return `${dayMonth(weekStart)} – ${dayMonth(weekEnd(weekStart))}`;
}

export interface WeekSelectProps {
  /** The Monday in view (`yyyy-mm-dd`). */
  value: string;
  /** The LIVE week's Monday — the pivot the list is generated around. */
  thisWeek: string;
  onPick: (weekStart: string) => void;
}

export function WeekSelect({ value, thisWeek, onPick }: WeekSelectProps) {
  const [open, setOpen] = React.useState(false);

  // The list: a window of Mondays around the live week, plus the viewed week
  // itself — stepping past the window (or landing on a deep-linked `?week=`)
  // must never drop the current selection out of its own dropdown.
  const { upcoming, past } = React.useMemo(() => {
    const mondays = new Set<string>();
    for (let i = -PAST_WEEKS; i <= UPCOMING_WEEKS; i++) mondays.add(addDays(thisWeek, i * 7));
    mondays.add(value);
    const all = Array.from(mondays).sort(); // yyyy-mm-dd sorts chronologically
    return {
      // Nearest-first in both directions: upcoming reads forward (W20, W21, W22),
      // past reads backward (W18, W17, W16).
      upcoming: all.filter((w) => w > thisWeek),
      past: all.filter((w) => w < thisWeek).reverse(),
    };
  }, [thisWeek, value]);

  const weekNo = weekNoOf(value);
  const range = formatWeekRangeShort(value);

  function pick(weekStart: string) {
    setOpen(false);
    if (weekStart !== value) onPick(weekStart);
  }

  return (
    <div className="inline-flex shrink-0 items-center overflow-hidden rounded-lg border border-hairline-strong bg-surface-card">
      <button
        type="button"
        aria-label="Previous week"
        onClick={() => onPick(prevWeekStart(value))}
        className={`cursor-pointer px-1 py-0.5 text-ink-subtle transition-colors hover:bg-surface-soft hover:text-altus-red ${FOCUS_RING}`}
      >
        <ChevronLeft size={11} strokeWidth={2.4} />
      </button>

      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <button
            type="button"
            aria-label={`Week ${weekNo}, ${range} — pick a week`}
            className={`flex cursor-pointer items-center gap-1 border-x border-hairline-strong px-1.5 py-0.5 transition-colors hover:bg-surface-soft ${FOCUS_RING}`}
          >
            <CalendarDays size={11} className="text-ink-subtle" />
            <span className="text-[10.5px] font-bold tabular-nums text-altus-red">W{weekNo}</span>
            <span className="text-[10.5px] font-bold text-ink-subtle">·</span>
            <span className="whitespace-nowrap text-[10.5px] font-bold tabular-nums text-ink-strong">
              {range}
            </span>
            <ChevronDown
              size={11}
              strokeWidth={2.6}
              className={`text-ink-subtle transition-transform ${open ? "rotate-180" : ""}`}
            />
          </button>
        </PopoverTrigger>

        {/* Compact and scrolling — a fixed max height (still capped by the space
            actually available, so it never runs off a short viewport) is what
            keeps 20+ weeks from becoming a full-page menu. */}
        <PopoverContent
          align="center"
          className="max-h-[min(340px,var(--radix-popover-content-available-height))] w-[236px] p-1.5"
        >
          <WeekGroup label="Upcoming" weeks={upcoming} selected={value} onPick={pick} />
          <WeekGroup label="Current" weeks={[thisWeek]} selected={value} onPick={pick} isCurrent />
          <WeekGroup label="Past" weeks={past} selected={value} onPick={pick} />
        </PopoverContent>
      </Popover>

      <button
        type="button"
        aria-label="Next week"
        onClick={() => onPick(nextWeekStart(value))}
        className={`cursor-pointer px-1 py-0.5 text-ink-subtle transition-colors hover:bg-surface-soft hover:text-altus-red ${FOCUS_RING}`}
      >
        <ChevronRight size={11} strokeWidth={2.4} />
      </button>
    </div>
  );
}

/** One labelled band of the list (UPCOMING / CURRENT / PAST). The heading sticks
 *  so the group a row belongs to stays readable while the list scrolls. */
function WeekGroup({
  label,
  weeks,
  selected,
  onPick,
  isCurrent = false,
}: {
  label: string;
  weeks: string[];
  selected: string;
  onPick: (weekStart: string) => void;
  isCurrent?: boolean;
}) {
  if (weeks.length === 0) return null;
  return (
    <div role="group" aria-label={label}>
      <div
        className="sticky top-0 z-10 px-2 pb-1 pt-1.5 text-[9.5px] font-bold uppercase tracking-[0.14em] text-ink-subtle"
        style={{ background: "var(--color-surface-card)" }}
      >
        {label}
      </div>
      {weeks.map((w) => (
        <WeekRow
          key={w}
          weekStart={w}
          active={w === selected}
          isCurrent={isCurrent}
          onPick={() => onPick(w)}
        />
      ))}
    </div>
  );
}

function WeekRow({
  weekStart,
  active,
  isCurrent,
  onPick,
}: {
  weekStart: string;
  active: boolean;
  isCurrent: boolean;
  onPick: () => void;
}) {
  const weekNo = weekNoOf(weekStart);
  const range = formatWeekRangeShort(weekStart);
  return (
    <button
      type="button"
      onClick={onPick}
      aria-current={active ? "true" : undefined}
      aria-label={`Week ${weekNo}, ${range}${isCurrent ? " (this week)" : ""}`}
      className={`flex w-full cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-left transition-colors hover:bg-surface-soft ${FOCUS_RING}`}
      style={
        active
          ? { background: "color-mix(in srgb, var(--color-altus-red) 8%, transparent)" }
          : undefined
      }
    >
      <span
        className="w-[30px] shrink-0 text-[12.5px] font-bold tabular-nums"
        style={{ color: active || isCurrent ? "var(--color-altus-red)" : "var(--color-ink-strong)" }}
      >
        W{weekNo}
      </span>
      <span className="flex-1 truncate text-[12px] font-medium tabular-nums text-ink-soft">
        {range}
      </span>
      {active && <Check size={13} strokeWidth={3} className="shrink-0 text-altus-red" />}
    </button>
  );
}

/** Mirrors the board's shared focus ring (kept local so this file stands alone). */
const FOCUS_RING =
  "outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-altus-red)]/60 focus-visible:ring-offset-1 focus-visible:ring-offset-[var(--color-surface-soft)]";
