"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { SalaryLineageData } from "@/lib/queries/salary-lineage";

const money = (value: number | null | undefined) => value == null ? "—" : `₹${value.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString("en-IN") : "—";

function Metric({ label, value, source }: { label: string; value: string; source: string }) {
  return <details className="rounded-lg border border-hairline bg-white">
    <summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-4 py-3">
      <span className="text-[13px] font-medium text-ink-soft">{label}</span>
      <span className="text-[15px] font-semibold tabular-nums text-ink-strong">{value}</span>
    </summary>
    <div className="border-t border-hairline px-4 py-3 text-[12px] leading-5 text-ink-subtle">{source}</div>
  </details>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-xl border border-hairline bg-[#F8FAFC] p-4">
    <h2 className="mb-3 text-[14px] font-semibold text-ink-strong">{title}</h2>
    {children}
  </section>;
}

export function SalaryLineageView({ data, employees, months }: { data: SalaryLineageData | null; employees: Array<{ id: string; name: string }>; months: string[] }) {
  const router = useRouter();
  const pathname = usePathname();
  const params = useSearchParams();
  const employeeId = params.get("employee") ?? data?.employee.id ?? employees[0]?.id ?? "";
  const month = params.get("month") ?? data?.month ?? months[0] ?? "";
  const choose = (key: string, value: string) => {
    const next = new URLSearchParams(params.toString());
    if (value) next.set(key, value); else next.delete(key);
    router.push(`${pathname}?${next.toString()}`);
  };

  if (!data) return <div className="rounded-xl border border-hairline bg-white p-6 text-sm text-ink-subtle">No salary profile found.</div>;

  const r = data.run;
  const b = data.breakup;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-end gap-3 rounded-xl border border-hairline bg-white p-4">
      <label className="grid gap-1 text-[12px] font-medium text-ink-subtle">Employee
        <select value={employeeId} onChange={(e) => choose("employee", e.target.value)} className="min-w-[220px] rounded-md border border-hairline bg-white px-3 py-2 text-sm text-ink-strong">
          {employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}
        </select>
      </label>
      <label className="grid gap-1 text-[12px] font-medium text-ink-subtle">Salary period
        <select value={month} onChange={(e) => choose("month", e.target.value)} className="rounded-md border border-hairline bg-white px-3 py-2 text-sm text-ink-strong">
          {months.map((item) => <option key={item} value={item}>{item}</option>)}
        </select>
      </label>
      <div className="ml-auto text-right text-[12px] text-ink-subtle">Read-only lineage<br /><span className="text-ink-soft">Sources stay unchanged</span></div>
    </div>

    <Section title="Salary overview">
      <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-4">
        <Metric label="CTC" value={money(data.profile?.annualCtc)} source="Source: salary_profiles.annual_ctc. Current employee profile; no monthly CTC history table exists." />
        <Metric label="Gross salary" value={money(r?.gross ?? b?.payableAfterLeave)} source={r ? `Source: salary_runs.gross. Generated by ${r.source}; formula is selected by pay basis in lib/salary/generate.ts.` : "No salary_runs row for selected employee and month."} />
        <Metric label="Deductions" value={money((r?.pt ?? b?.pt ?? 0) + (r?.tds ?? 0) + (r?.advances ?? b?.advance ?? 0))} source="Components: Professional Tax, TDS and salary advance. Values below come from stored payroll fields." />
        <Metric label="Net pay" value={money(r?.netPayable ?? b?.finalPayment)} source={r ? "Source: salary_runs.net_payable. Canonical formula: gross − PT − TDS − advances + pending balance in." : "Source: salary_breakup.final_payment. No canonical salary run exists for this period."} />
      </div>
    </Section>

    <div className="grid gap-4 xl:grid-cols-2">
      <Section title="Salary profile and breakup">
        <div className="space-y-2 text-[13px]">
          <Line label="Employee" value={`${data.employee.name} · ${data.employee.email}`} />
          <Line label="Pay basis" value={data.profile?.payType ?? "No profile"} />
          <Line label="Monthly CTC" value={money(data.profile?.monthlyCtc)} />
          <Line label="TDS configured" value={money(data.profile?.tdsMonthly)} />
          <Line label="PT exemption" value={data.profile?.ptExempt ? "Yes" : "No"} />
          {data.ctcBreakup ? <>
            <div className="border-t border-hairline pt-2 font-medium text-ink-strong">Component source: salary_ctc_breakup</div>
            {data.ctcBreakup.components.length ? data.ctcBreakup.components.map((item) => <Line key={item.label} label={item.label} value={`${money(item.annual)} annual`} />) : <Line label="Components" value="No component rows stored" />}
            <Line label="Breakup updated" value={date(data.ctcBreakup.updatedAt)} />
          </> : <p className="rounded-md bg-amber-50 px-3 py-2 text-[12px] text-amber-900">No salary_ctc_breakup row. CTC still comes from salary_profiles.</p>}
        </div>
      </Section>

      <Section title="Calculation trace">
        {r ? <div className="space-y-2 text-[13px]">
          <Line label="Payroll row" value={`${r.month} · ${r.id}`} />
          <Line label="Frozen monthly salary" value={money(r.monthlySalary)} />
          <Line label="Frozen daily salary" value={money(r.perDaySalary)} />
          <Line label="Frozen schedule hours/day" value={r.workingHoursPerDay == null ? "Historical run" : `${r.workingHoursPerDay} h`} />
          <Line label="Payable days" value={String(r.payableDays)} />
          <Line label="Pay type" value={r.payType} />
          <Line label="Worked / target hours" value={r.workedHours == null ? "Not stored" : `${r.workedHours} / ${r.targetHours ?? "—"}`} />
          <Line label="Hourly rate" value={money(r.hourlyRate)} />
          <Line label="Overtime" value={`${r.overtimeHours} h · ${money(r.overtimeAmount)}`} />
          <Line label="Professional Tax" value={money(r.pt)} />
          <Line label="TDS" value={money(r.tds)} />
          <Line label="Advances" value={money(r.advances)} />
          <Line label="Pending balance in" value={money(r.pendingBalanceIn)} />
          <Line label="Run created" value={date(r.createdAt)} />
        </div> : <p className="text-[13px] text-ink-subtle">No salary run stored for this employee and period. No calculation trace can be claimed.</p>}
      </Section>
    </div>

    <div className="grid gap-4 xl:grid-cols-2">
      <Section title="Tax and deductions">
        <div className="space-y-2 text-[13px]"><Line label="Taxable salary source" value="No separate taxable-income table found" /><Line label="TDS source" value={r ? "salary_runs.tds, populated from salary_profiles.tds_monthly" : "salary_profiles.tds_monthly only"} /><Line label="Professional Tax source" value={r ? "salary_runs.pt, calculated by existing pay engine and PT exemption policy" : "No monthly run value"} /><Line label="Tax formula" value="Existing engine: net = gross − PT − TDS − advances + pending balance in" /></div>
      </Section>
      <Section title="Attendance and advances">
        <div className="space-y-2 text-[13px]">
          <Line label="Manual waive-off" value={b && b.waiveOffDays > 0 ? `${b.waiveOffDays} days · ${b.waiveOffNote ?? "No reason stored"}` : "None"} />
          <Line label="Manual payout adjustment" value={b && b.payoutAdjustment !== 0 ? `${money(b.payoutAdjustment)} · ${b.payoutAdjustmentNote ?? "No reason stored"}` : "None"} />
        </div>
        <div className="space-y-2 text-[13px]"><Line label="Attendance input" value={r ? `${r.payableDays} payable days stored on salary_runs` : "No stored payroll attendance input"} /><Line label="Advances this period" value={data.advances.length ? data.advances.map((item) => `${money(item.amount)} · ${item.advanceDate ?? "undated"}`).join("; ") : "None"} /><Line label="Breakup mirror" value={b ? `salary_breakup · final payment ${money(b.finalPayment)}` : "No linked salary_breakup row"} /></div>
      </Section>
    </div>

    <Section title="Forward connections">
      <div className="grid gap-3 md:grid-cols-3">
        <Connection title="Payroll" text={r ? `Linked salary_runs row. Disbursed: ${r.disbursed ? "Yes" : "No"}. Amount: ${money(r.disbursedAmount ?? r.netPayable)}.` : "No salary run link for selected period."} />
        <Connection title="Accounts" text={b ? "Linked salary_breakup register row. This is the existing Accounts-facing salary register." : "No salary_breakup row for selected period."} />
        <Connection title="Payments" text={data.payments.length ? data.payments.map((item) => `${money(item.amount)} · ${item.method ?? "method not stored"}`).join("; ") : "No salary_payments row for selected period."} />
        <Connection title="Reimbursements" text={data.reimbursements.lines.length ? `${data.reimbursements.lines.length} module submission record(s); paid this month ${money(data.reimbursements.paidThisMonth)}.` : "No reimbursement records for selected period."} />
        <Connection title="Assets" text={data.assets.length ? `${data.assets.length} HR asset record(s) linked to employee. No salary deduction or recovery link found.` : "No direct connection found."} />
        <Connection title="Accounting ledger" text="No direct salary-to-ledger/account-entry relation found in current schema." />
      </div>
    </Section>

    <Section title="Change history">
      {data.audit.length ? <div className="space-y-2">{data.audit.map((event, index) => <details key={`${event.createdAt}-${index}`} className="rounded-md border border-hairline bg-white px-3 py-2 text-[12px]"><summary className="cursor-pointer font-medium text-ink-soft">{event.eventType} · {date(event.createdAt)}</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap text-ink-subtle">{JSON.stringify({ from: event.fromValue, to: event.toValue, note: event.note }, null, 2)}</pre></details>)}</div> : <p className="text-[13px] text-ink-subtle">No salary profile history events found.</p>}
    </Section>
  </div>;
}

function Line({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b border-hairline/70 pb-1"><span className="text-ink-subtle">{label}</span><span className="text-right font-medium text-ink-soft">{value}</span></div>; }
function Connection({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border border-hairline bg-white p-3"><div className="mb-1 text-[13px] font-semibold text-ink-strong">{title}</div><p className="text-[12px] leading-5 text-ink-subtle">{text}</p></div>; }
