"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Check, Copy, Eye, EyeOff, FileText, Image as ImageIcon, Loader2, Paperclip, Plus, Search, Trash2 } from "lucide-react";
import { fireToast } from "@/lib/toast";
import { formatDateHr } from "@/lib/format";
import { getSupabaseClient } from "@/lib/supabase/browser";
import { ASSET_TYPES, assetPrefix } from "@/lib/hr/registers";
import type { AssetPerson, AssetRow } from "@/lib/hr/registers-server";
import type { HrAssetIssuedKind } from "@/db/schema";
import { saveAsset, deleteAsset, revealAssetPassword, createAssetUploadUrl } from "@/app/(app)/hr/assets/actions";
import { FILTER, Field, INPUT, Modal, NativeSelect, PASS_VERTICAL_SCROLL, RED, TD, TH } from "./register-ui";

type Draft = {
  id?: string;
  assetCode?: string;
  assetType: string;
  assetName: string;
  location: string;
  serialNo: string;
  model: string;
  make: string;
  description: string;
  specifications: string;
  warrantyUntil: string;
  underAmc: boolean;
  vendorName: string;
  photoPath: string | null;
  photoUrl: string | null;
  invoicePath: string | null;
  invoiceUrl: string | null;
  issuedKind: HrAssetIssuedKind;
  issuedEmployeeId: string;
  issuedOffice: string;
  notes: string;
  username: string;
  hasPassword: boolean;
  password: string;
  clearPassword: boolean;
};

function draftFrom(a?: AssetRow): Draft {
  return {
    id: a?.id,
    assetCode: a?.assetCode,
    assetType: a?.assetType ?? "",
    assetName: a?.assetName ?? "",
    location: a?.location ?? "",
    serialNo: a?.serialNo ?? "",
    model: a?.model ?? "",
    make: a?.make ?? "",
    description: a?.description ?? "",
    specifications: a?.specifications ?? "",
    warrantyUntil: a?.warrantyUntil ?? "",
    underAmc: a?.underAmc ?? false,
    vendorName: a?.vendorName ?? "",
    photoPath: a?.photoPath ?? null,
    photoUrl: a?.photoUrl ?? null,
    invoicePath: a?.invoicePath ?? null,
    invoiceUrl: a?.invoiceUrl ?? null,
    issuedKind: a?.issuedKind ?? "none",
    issuedEmployeeId: a?.issuedEmployeeId ?? "",
    issuedOffice: a?.issuedOffice ?? "",
    notes: a?.notes ?? "",
    username: a?.username ?? "",
    hasPassword: a?.hasPassword ?? false,
    password: "",
    clearPassword: false,
  };
}

function issuedLabel(a: Pick<AssetRow, "issuedKind" | "issuedEmployeeName" | "issuedOffice">): string {
  if (a.issuedKind === "person") return a.issuedEmployeeName ?? "Person (removed)";
  if (a.issuedKind === "office") return a.issuedOffice ? `Office · ${a.issuedOffice}` : "Office";
  return "Not Issued";
}

/**
 * HR → Asset Register. Codes are generated by the server per type (LAP-0001).
 * Ruchita, Rutvisha and Manan add, edit and delete; everyone else opens a
 * read-only view. Usernames and passwords are never sent to viewers, and a
 * password is only decrypted when an editor presses "Show".
 */
export function AssetRegister({
  assets,
  people,
  canEdit,
}: {
  assets: AssetRow[];
  people: AssetPerson[];
  canEdit: boolean;
}) {
  const router = useRouter();
  const [q, setQ] = React.useState("");
  const [type, setType] = React.useState("all");
  const [issued, setIssued] = React.useState<"all" | HrAssetIssuedKind>("all");
  const [draft, setDraft] = React.useState<Draft | null>(null);
  const [busy, setBusy] = React.useState<string | null>(null);

  const needle = q.trim().toLowerCase();
  const rows = assets
    .filter((a) => type === "all" || a.assetType === type)
    .filter((a) => issued === "all" || a.issuedKind === issued)
    .filter(
      (a) =>
        !needle ||
        [a.assetCode, a.assetType, a.assetName, a.make, a.model, a.serialNo, a.location, a.vendorName, issuedLabel(a)].some((v) =>
          (v ?? "").toLowerCase().includes(needle),
        ),
    );

  async function save(e: React.FormEvent) {
    e.preventDefault();
    if (!draft || !canEdit) return;
    setBusy("save");
    const res = await saveAsset({
      id: draft.id,
      assetType: draft.assetType,
      assetName: draft.assetName,
      location: draft.location,
      serialNo: draft.serialNo,
      model: draft.model,
      make: draft.make,
      description: draft.description,
      specifications: draft.specifications,
      warrantyUntil: draft.warrantyUntil,
      underAmc: draft.underAmc,
      vendorName: draft.vendorName,
      photoPath: draft.photoPath,
      invoicePath: draft.invoicePath,
      issuedKind: draft.issuedKind,
      issuedEmployeeId: draft.issuedEmployeeId || null,
      issuedOffice: draft.issuedOffice,
      notes: draft.notes,
      username: draft.username,
      password: draft.password || undefined,
      clearPassword: draft.clearPassword,
    }).catch((err: unknown) => ({ ok: false as const, error: err instanceof Error ? err.message : "Could not save." }));
    setBusy(null);
    if (!res.ok) {
      fireToast({ message: res.error, type: "error" });
      return;
    }
    fireToast({ message: draft.id ? `${res.assetCode} updated` : `${res.assetCode} added`, type: "success" });
    setDraft(null);
    router.refresh();
  }

  async function remove(a: AssetRow) {
    if (!window.confirm(`Delete ${a.assetCode} (${a.assetName})? This can't be undone.`)) return;
    setBusy(`del-${a.id}`);
    const res = await deleteAsset(a.id);
    setBusy(null);
    if (!res.ok) {
      fireToast({ message: res.error, type: "error" });
      return;
    }
    fireToast({ message: `${a.assetCode} deleted`, type: "success" });
    setDraft(null);
    router.refresh();
  }

  const readOnly = !canEdit;

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative w-[260px] max-w-full">
          <Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-ink-subtle" />
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search code, make, serial, person…" aria-label="Search assets" className={`${INPUT} pl-9`} />
        </div>
        <NativeSelect value={type} onChange={(e) => setType(e.target.value)} aria-label="Filter by asset" className={FILTER}>
          <option value="all">All assets</option>
          {ASSET_TYPES.map((t) => (
            <option key={t.label} value={t.label}>
              {t.label}
            </option>
          ))}
        </NativeSelect>
        <NativeSelect value={issued} onChange={(e) => setIssued(e.target.value as typeof issued)} aria-label="Filter by issued to" className={FILTER}>
          <option value="all">Issued to: anyone</option>
          <option value="person">Issued to a person</option>
          <option value="office">Issued to an office</option>
          <option value="none">Not Issued</option>
        </NativeSelect>
        {canEdit ? (
          <button
            type="button"
            onClick={() => setDraft(draftFrom())}
            className="ml-auto inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-[14px] font-bold text-white"
            style={{ background: `linear-gradient(135deg, ${RED}, var(--color-altus-red-deep))` }}
          >
            <Plus size={16} strokeWidth={2.6} /> Add asset
          </button>
        ) : (
          <span className="ml-auto text-[12.5px] font-semibold text-ink-muted">View only — Ruchita, Rutvisha and Manan can make changes.</span>
        )}
      </div>

      <section className="rounded-2xl border border-hairline-strong bg-white">
        {/* Inline overscroll style — see PASS_VERTICAL_SCROLL in register-ui.tsx. */}
        <div className="overflow-x-auto" style={PASS_VERTICAL_SCROLL}>
          <table className="w-full border-collapse">
            <thead className="bg-surface-soft">
              <tr>
                <th className={TH}>S. No.</th>
                <th className={TH}>Asset Code</th>
                <th className={TH}>Asset Name</th>
                <th className={TH}>Make / Model</th>
                <th className={TH}>Serial No</th>
                <th className={TH}>Location</th>
                <th className={TH}>Issued To</th>
                <th className={TH}>Warranty</th>
                <th className={TH}>AMC</th>
                <th className={TH}><span className="sr-only">Actions</span></th>
              </tr>
            </thead>
            <tbody>
              {rows.map((a, i) => (
                <tr key={a.id} className="cursor-pointer border-t border-hairline hover:bg-surface-soft/60" onClick={() => setDraft(draftFrom(a))}>
                  <td className={`${TD} tabular-nums text-ink-muted`}>{i + 1}</td>
                  <td className={`${TD} whitespace-nowrap font-mono text-[12.5px] font-bold`}>{a.assetCode}</td>
                  <td className={TD}>
                    <span className="font-bold">{a.assetName}</span>
                    {a.assetName !== a.assetType ? <span className="block text-[12px] text-ink-muted">{a.assetType}</span> : null}
                  </td>
                  <td className={TD}>{[a.make, a.model].filter(Boolean).join(" · ") || "—"}</td>
                  <td className={`${TD} font-mono text-[12.5px]`}>{a.serialNo ?? "—"}</td>
                  <td className={TD}>{a.location ?? "—"}</td>
                  <td className={TD}>{issuedLabel(a)}</td>
                  <td className={`${TD} whitespace-nowrap`}>{a.warrantyUntil ? formatDateHr(a.warrantyUntil) : "—"}</td>
                  <td className={TD}>{a.underAmc ? "Yes" : "No"}</td>
                  <td className={`${TD} whitespace-nowrap`} onClick={(e) => e.stopPropagation()}>
                    <div className="flex items-center justify-end gap-1.5">
                      {a.photoUrl ? (
                        <a href={a.photoUrl} target="_blank" rel="noreferrer" title="Photo" aria-label="Open photo" className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-hairline-strong text-ink-muted hover:text-ink-strong">
                          <ImageIcon size={14} />
                        </a>
                      ) : null}
                      {a.invoiceUrl ? (
                        <a href={a.invoiceUrl} target="_blank" rel="noreferrer" title="Original invoice" aria-label="Open original invoice" className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-hairline-strong text-ink-muted hover:text-ink-strong">
                          <FileText size={14} />
                        </a>
                      ) : null}
                      {canEdit ? (
                        <button type="button" onClick={() => remove(a)} disabled={busy === `del-${a.id}`} title="Delete" aria-label={`Delete ${a.assetCode}`} className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-hairline-strong text-ink-muted hover:text-[color:var(--color-altus-red)] disabled:opacity-50">
                          {busy === `del-${a.id}` ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />}
                        </button>
                      ) : null}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {rows.length === 0 ? (
            <p className="px-4 py-8 text-center text-[13.5px] text-ink-muted">{assets.length === 0 ? "No assets registered yet." : "No assets match."}</p>
          ) : null}
        </div>
      </section>

      {draft ? (
        <Modal
          wide
          title={draft.id ? `${draft.assetCode} · ${draft.assetName}` : "Add asset"}
          onClose={() => setDraft(null)}
        >
          <form onSubmit={save} className="grid grid-cols-2 gap-3 max-sm:grid-cols-1">
            <fieldset disabled={readOnly} className="contents">
              <Field label="Asset Name" required>
                <NativeSelect
                  value={draft.assetType}
                  onChange={(e) => {
                    const t = e.target.value;
                    // The name follows the type until someone types their own.
                    const followsType = !draft.assetName || draft.assetName === draft.assetType;
                    setDraft({ ...draft, assetType: t, assetName: followsType ? t : draft.assetName });
                  }}
                  required
                  className={INPUT}
                >
                  <option value="" disabled>
                    Choose…
                  </option>
                  {ASSET_TYPES.map((t) => (
                    <option key={t.label} value={t.label}>
                      {t.label}
                    </option>
                  ))}
                </NativeSelect>
              </Field>
              <Field label="Asset Code">
                <input
                  value={draft.assetCode ?? (draft.assetType ? `${assetPrefix(draft.assetType)}-#### (auto)` : "Generated on save")}
                  disabled
                  className={`${INPUT} font-mono`}
                />
              </Field>
              {draft.assetType === "Other" || (draft.assetName && draft.assetName !== draft.assetType) ? (
                <Field label="Name / Label" required className="col-span-2 max-sm:col-span-1">
                  <input value={draft.assetName} onChange={(e) => setDraft({ ...draft, assetName: e.target.value })} required className={INPUT} />
                </Field>
              ) : null}
              <Field label="Make">
                <input value={draft.make} onChange={(e) => setDraft({ ...draft, make: e.target.value })} placeholder="Dell, HP, Apple…" className={INPUT} />
              </Field>
              <Field label="Model">
                <input value={draft.model} onChange={(e) => setDraft({ ...draft, model: e.target.value })} className={INPUT} />
              </Field>
              <Field label="Serial No">
                <input value={draft.serialNo} onChange={(e) => setDraft({ ...draft, serialNo: e.target.value })} className={`${INPUT} font-mono`} />
              </Field>
              <Field label="Location">
                <input value={draft.location} onChange={(e) => setDraft({ ...draft, location: e.target.value })} className={INPUT} />
              </Field>
              <Field label="Description" className="col-span-2 max-sm:col-span-1">
                <textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} rows={2} className={INPUT} />
              </Field>
              <Field label="Specifications" className="col-span-2 max-sm:col-span-1">
                <textarea value={draft.specifications} onChange={(e) => setDraft({ ...draft, specifications: e.target.value })} rows={2} placeholder="e.g. i5 / 16 GB RAM / 512 GB SSD" className={INPUT} />
              </Field>
              <Field label="Warranty till">
                <input type="date" value={draft.warrantyUntil} onChange={(e) => setDraft({ ...draft, warrantyUntil: e.target.value })} className={INPUT} />
              </Field>
              <Field label="Under AMC">
                <div className="flex gap-1.5">
                  {[true, false].map((v) => (
                    <button
                      key={String(v)}
                      type="button"
                      onClick={() => setDraft({ ...draft, underAmc: v })}
                      className="flex-1 rounded-lg px-2 py-2 text-[13px] font-bold"
                      style={draft.underAmc === v ? { background: "color-mix(in srgb, var(--color-altus-red) 12%, transparent)", color: RED, boxShadow: `inset 0 0 0 1.5px ${RED}` } : { background: "var(--color-surface-soft)", color: "var(--color-ink-muted)", boxShadow: "inset 0 0 0 1px var(--color-hairline)" }}
                    >
                      {v ? "Yes" : "No"}
                    </button>
                  ))}
                </div>
              </Field>
              <Field label="Vendor Name" className="col-span-2 max-sm:col-span-1">
                <input value={draft.vendorName} onChange={(e) => setDraft({ ...draft, vendorName: e.target.value })} className={INPUT} />
              </Field>

              <Field label="Issued To">
                <NativeSelect
                  value={draft.issuedKind}
                  onChange={(e) => setDraft({ ...draft, issuedKind: e.target.value as HrAssetIssuedKind })}
                  className={INPUT}
                >
                  <option value="none">Not Issued</option>
                  <option value="person">Person</option>
                  <option value="office">Office</option>
                </NativeSelect>
              </Field>
              {draft.issuedKind === "person" ? (
                <Field label="Person Name" required>
                  <NativeSelect value={draft.issuedEmployeeId} onChange={(e) => setDraft({ ...draft, issuedEmployeeId: e.target.value })} required className={INPUT}>
                    <option value="" disabled>
                      Choose…
                    </option>
                    {people.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.name}
                      </option>
                    ))}
                    {draft.issuedEmployeeId && !people.some((p) => p.id === draft.issuedEmployeeId) ? (
                      <option value={draft.issuedEmployeeId}>(former employee)</option>
                    ) : null}
                  </NativeSelect>
                </Field>
              ) : draft.issuedKind === "office" ? (
                <Field label="Office" required>
                  <input value={draft.issuedOffice} onChange={(e) => setDraft({ ...draft, issuedOffice: e.target.value })} required className={INPUT} />
                </Field>
              ) : (
                <div />
              )}
            </fieldset>

            <FileSlot
              label="Photo"
              kind="photo"
              accept="image/*"
              path={draft.photoPath}
              url={draft.photoUrl}
              readOnly={readOnly}
              onUploaded={(path) => setDraft((d) => (d ? { ...d, photoPath: path, photoUrl: null } : d))}
              onClear={() => setDraft((d) => (d ? { ...d, photoPath: null, photoUrl: null } : d))}
            />
            <FileSlot
              label="Original Invoice"
              kind="invoice"
              accept="application/pdf,image/*"
              path={draft.invoicePath}
              url={draft.invoiceUrl}
              readOnly={readOnly}
              onUploaded={(path) => setDraft((d) => (d ? { ...d, invoicePath: path, invoiceUrl: null } : d))}
              onClear={() => setDraft((d) => (d ? { ...d, invoicePath: null, invoiceUrl: null } : d))}
            />

            <fieldset disabled={readOnly} className="contents">
              <Field label="Notes" className="col-span-2 max-sm:col-span-1">
                <textarea value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} rows={2} className={INPUT} />
              </Field>
            </fieldset>

            {canEdit ? (
              <>
                <Field label="Username">
                  <input value={draft.username} onChange={(e) => setDraft({ ...draft, username: e.target.value })} autoComplete="off" className={INPUT} />
                </Field>
                <PasswordField draft={draft} setDraft={setDraft} />
              </>
            ) : null}

            <div className="col-span-2 flex items-center justify-end gap-2 max-sm:col-span-1">
              {readOnly ? (
                <button type="button" onClick={() => setDraft(null)} className="rounded-lg border border-hairline-strong px-4 py-2 text-[13.5px] font-bold text-ink-strong">
                  Close
                </button>
              ) : (
                <>
                  <button type="button" onClick={() => setDraft(null)} className="rounded-lg border border-hairline-strong px-4 py-2 text-[13.5px] font-bold text-ink-strong">
                    Cancel
                  </button>
                  <button type="submit" disabled={busy === "save"} className="inline-flex items-center gap-2 rounded-lg px-5 py-2 text-[13.5px] font-bold text-white disabled:opacity-60" style={{ background: RED }}>
                    {busy === "save" ? <Loader2 size={15} className="animate-spin" /> : null} Save
                  </button>
                </>
              )}
            </div>
          </form>
        </Modal>
      ) : null}
    </div>
  );
}

function FileSlot({
  label,
  kind,
  accept,
  path,
  url,
  readOnly,
  onUploaded,
  onClear,
}: {
  label: string;
  kind: "photo" | "invoice";
  accept: string;
  path: string | null;
  url: string | null;
  readOnly: boolean;
  onUploaded: (path: string) => void;
  onClear: () => void;
}) {
  const [uploading, setUploading] = React.useState(false);

  async function pick(file: File) {
    setUploading(true);
    try {
      const signed = await createAssetUploadUrl({ kind, fileName: file.name, mime: file.type || null, size: file.size });
      if (!signed.ok) {
        fireToast({ message: signed.error, type: "error" });
        return;
      }
      const { error } = await getSupabaseClient()
        .storage.from(signed.bucket)
        .uploadToSignedUrl(signed.path, signed.token, file, { contentType: file.type || "application/octet-stream" });
      if (error) {
        fireToast({ message: `Upload failed: ${error.message}`, type: "error" });
        return;
      }
      onUploaded(signed.path);
    } finally {
      setUploading(false);
    }
  }

  return (
    <Field label={label}>
      <div className="flex min-h-[40px] items-center gap-2 rounded-lg border border-hairline-strong bg-surface-soft px-2.5 py-1.5">
        <Paperclip size={14} className="shrink-0 text-ink-subtle" />
        <span className="min-w-0 flex-1 truncate text-[12.5px] font-semibold text-ink-muted">
          {uploading ? "Uploading…" : path ? (url ? "Attached" : "Attached — save to keep") : "No file"}
        </span>
        {url ? (
          <a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-pill bg-white px-2 py-0.5 text-[11px] font-bold text-ink-soft hover:text-ink-strong">
            <Eye size={11} /> View
          </a>
        ) : null}
        {!readOnly ? (
          <>
            {path ? (
              <button type="button" onClick={onClear} className="rounded-pill bg-white px-2 py-0.5 text-[11px] font-bold text-ink-soft hover:text-[color:var(--color-altus-red)]">
                Remove
              </button>
            ) : null}
            <label className="cursor-pointer rounded-pill bg-white px-2 py-0.5 text-[11px] font-bold text-ink-soft hover:text-ink-strong">
              {uploading ? <Loader2 size={11} className="animate-spin" /> : path ? "Replace" : "Choose"}
              <input type="file" accept={accept} className="sr-only" disabled={uploading} onChange={(e) => e.target.files?.[0] && pick(e.target.files[0])} />
            </label>
          </>
        ) : null}
      </div>
    </Field>
  );
}

function PasswordField({ draft, setDraft }: { draft: Draft; setDraft: React.Dispatch<React.SetStateAction<Draft | null>> }) {
  const [shown, setShown] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [copied, setCopied] = React.useState(false);

  async function reveal() {
    if (!draft.id) return;
    if (shown !== null) {
      setShown(null);
      return;
    }
    setLoading(true);
    const res = await revealAssetPassword(draft.id);
    setLoading(false);
    if (!res.ok) {
      fireToast({ message: res.error, type: "error" });
      return;
    }
    setShown(res.password);
  }

  return (
    <Field label="Password">
      <input
        type="password"
        value={draft.password}
        onChange={(e) => setDraft((d) => (d ? { ...d, password: e.target.value, clearPassword: false } : d))}
        placeholder={draft.hasPassword && !draft.clearPassword ? "•••••• (saved — type to change)" : "Stored encrypted"}
        autoComplete="new-password"
        className={INPUT}
      />
      {draft.id && draft.hasPassword && !draft.clearPassword ? (
        <div className="mt-1.5 flex flex-wrap items-center gap-2 text-[12px]">
          <button type="button" onClick={reveal} className="inline-flex items-center gap-1 font-bold text-ink-soft hover:text-ink-strong">
            {loading ? <Loader2 size={12} className="animate-spin" /> : shown !== null ? <EyeOff size={12} /> : <Eye size={12} />}
            {shown !== null ? "Hide" : "Show saved password"}
          </button>
          {shown !== null ? (
            <>
              <code className="rounded bg-surface-soft px-1.5 py-0.5 font-mono text-ink-strong">{shown}</code>
              <button
                type="button"
                onClick={() => {
                  void navigator.clipboard.writeText(shown).then(() => {
                    setCopied(true);
                    window.setTimeout(() => setCopied(false), 1500);
                  });
                }}
                className="inline-flex items-center gap-1 font-bold text-ink-soft hover:text-ink-strong"
              >
                {copied ? <Check size={12} /> : <Copy size={12} />} {copied ? "Copied" : "Copy"}
              </button>
            </>
          ) : null}
          <button
            type="button"
            onClick={() => {
              setShown(null);
              setDraft((d) => (d ? { ...d, password: "", clearPassword: true } : d));
            }}
            className="ml-auto font-bold text-ink-muted hover:text-[color:var(--color-altus-red)]"
          >
            Remove password
          </button>
        </div>
      ) : null}
    </Field>
  );
}
